module: temp-pod-manager

replicas: 1

ingress:
  enabled: true
  className: nginx
  host: myhost
  metadata:
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
  spec:
    path: /
    pathType: Prefix
  tls:
    enabled: true
    secretName: secret-https
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt

containers:
  name: pod-manager
  image: bitnami/kubectl
  tags: latest
  command: ["sh", "-c", "/scripts/pod-manager.sh"]
  ports:
    containerPort: 80 # This should be the port your app listens on (http : 80, https : 443)
  volumeMounts:
    name: pod-manager-scripts
    mountPath: /scripts
    readOnly: true
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 80

technicalSecret:
  enabled: false
  name: technical-secret

podManager:
  enabled: true
  ttl: 1800           # 30 minutes de TTL pour les pods temporaires
  rbac:
    rules:
      # Personnaliser les règles si nécessaire
      - apiGroups: [""]
        resources: ["pods", "services"]
        verbs: ["create", "delete", "get", "list"]
