{{/* Debug Values */}}
{{- printf "\nDEBUG Values:\n%s" (toYaml .Values | nindent 2) | printf "# %s" -}}
---

# templates/ingress.yaml
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "label-generator" . | nindent 4 }}
  name: {{ .Values.module }}-ingress
  annotations:
    {{- toYaml .Values.ingress.metadata.annotations | nindent 4 }}
    {{- if .Values.ingress.tls }}
    {{- toYaml .Values.ingress.tls.annotations | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName | default "secret-https" }}
  {{- end }}
  rules:
    {{- if .Values.ingress.host }}
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.spec.path | default "/" }}
            pathType: {{ .Values.ingress.spec.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ .Values.module }}-service
                port:
                  name: http
    {{- else }}
    - http:
        paths:
          - path: {{ .Values.ingress.spec.path | default "/" }}
            pathType: {{ .Values.ingress.spec.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ .Values.module }}-service
                port:
                  name: http
    {{- end }}
{{- end }}